// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CaseStudy struct {
	CaseNumber  string  `json:"caseNumber"`
	Description *string `json:"description,omitempty"`
}

type DeprecatedProduct struct {
	Sku       string  `json:"sku"`
	Package   string  `json:"package"`
	Reason    *string `json:"reason,omitempty"`
	CreatedBy *User   `json:"createdBy,omitempty"`
}

func (DeprecatedProduct) IsEntity() {}

type Inventory struct {
	ID                 string               `json:"id"`
	DeprecatedProducts []*DeprecatedProduct `json:"deprecatedProducts"`
}

func (Inventory) IsEntity() {}

type Product struct {
	ID         string             `json:"id"`
	Sku        *string            `json:"sku,omitempty"`
	Package    *string            `json:"package,omitempty"`
	Variation  *ProductVariation  `json:"variation,omitempty"`
	Dimensions *ProductDimension  `json:"dimensions,omitempty"`
	CreatedBy  *User              `json:"createdBy,omitempty"`
	Notes      *string            `json:"notes,omitempty"`
	Research   []*ProductResearch `json:"research"`
}

func (Product) IsEntity() {}

type ProductDimension struct {
	Size   *string  `json:"size,omitempty"`
	Weight *float64 `json:"weight,omitempty"`
	Unit   *string  `json:"unit,omitempty"`
}

type ProductResearch struct {
	Study   *CaseStudy `json:"study"`
	Outcome *string    `json:"outcome,omitempty"`
}

func (ProductResearch) IsEntity() {}

type ProductVariation struct {
	ID string `json:"id"`
}

type Query struct {
}

type User struct {
	AverageProductsCreatedPerYear *int    `json:"averageProductsCreatedPerYear,omitempty"`
	Email                         string  `json:"email"`
	Name                          *string `json:"name,omitempty"`
	TotalProductsCreated          *int    `json:"totalProductsCreated,omitempty"`
	YearsOfEmployment             int     `json:"yearsOfEmployment"`
}

func (User) IsEntity() {}
