serve:
  port: 4001
  browser: false
  endpoint: /

sources:
  - name: GraphQL API
    handler:
      graphql:
        schema: ./src/schema.ts
    transforms:
      - federation:
          types:
            - name: Product
              config:
                key:
                  - fields: "id"
                  - fields: "sku package"
                  - fields: "sku variation { id }"
                  # TODO: @key(fields: "sku package") (multi) not supported
                  # - sku package
                  # TODO: @key(fields: "sku variation { id }") (composite) not supported
                  # - sku variation { id }
                resolveReference: ./src/resolve-product.ts
                fields:
                  - name: createdBy
                    config:
                      provides:
                        fields: "totalProductsCreated"
                  - name: notes
                    config:
                      tag:
                        name: "internal"
                      # TODO: @tag(name: "internal") not supported
                      # tag: internal
            - name: DeprecatedProduct
              config:
                key:
                  - fields: "sku package"
                  # TODO: @key(fields: "sku package") (multi) not supported
                  # - sku package
                resolveReference: ./src/resolve-deprecated-product.ts
            - name: ProductResearch
              config:
                key:
                  - fields: "study { caseNumber }"
                # TODO: @key(fields: "study { caseNumber }") (composite) not supported
                # - study { caseNumber }
                resolveReference: ./src/resolve-product-research.ts
            - name: ProductDimension
              config:
                # TODO: @shareable not supported
                # shareable: true
                shareable: true
                fields:
                  - name: unit
                    config:
                      inaccessible: true
                      # TODO: @inaccessible not supported
                      # inaccessible: true
            - name: User
              config:
                key:
                  - fields: email
                fields:
                  - name: averageProductsCreatedPerYear
                    config:
                      # TODO: @requires(fields: "totalProductsCreated yearsOfEmployment") works? how to test?
                      requires:
                        - fields: "totalProductsCreated yearsOfEmployment"
                  - name: email
                    config:
                      external: true
                  - name: name
                    config:
                      override:
                        from: "users"
                      # TODO: @override(from: "users") not supported
                      # override: users
                  - name: totalProductsCreated
                    config:
                      external: true
                  - name: yearsOfEmployment
                    config:
                      external: true

plugins:
  - apolloInlineTrace: {}
