# Example Dockerfile from apollo-server
#
# FROM node:14-alpine
# WORKDIR /apollo-federation-testing/apollo-server
# COPY . /apollo-federation-testing/apollo-server
# RUN npm install
# EXPOSE 4001
# CMD [ "npm", "start" ]