services:
  products:
    # must be relative to the root of the project
    build:
      context: implementations/appsync
      args:
        SUBGRAPH_API_KEY: ${API_KEY}
        SUBGRAPH_URL: ${TEST_URL}
    ports:
      - 4001:4001