# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "apollo-federation", "~> 2"
gem "graphql", "~> 1.12"
gem "rack", "~> 2.2"
gem "rake", "~> 13.0"
gem "rerun", "~> 0.13.1"
gem "sinatra", "~> 2.1"
gem "thin", "~> 1.8"

gem "rb-kqueue", "~> 0.2.6"
