# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "apollo-federation", "~> 3.10"
gem "graphql", "~> 2.6"
gem "rack", "~> 3.2"
gem "rackup", "~> 2.3"
gem "rake", "~> 13.4"
gem "rerun", "~> 0.14.0"
gem "sinatra", "~> 4.2"
gem "puma", "~> 8.0"

gem "rb-kqueue", "~> 0.2"
