services:
  neo4j:
    image: "neo4j:enterprise"
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    healthcheck:
      test: wget http://localhost:7474/browser -O -
      interval: 1s
      timeout: 1s
      retries: 40
  products:
    build: implementations/neo4j-graphql
    ports:
      - 4001:4001
    environment:
      - NEO4J_URI=neo4j://neo4j:7687/neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      neo4j:
        condition: service_healthy
