name: Cleanup Old Releases

on:
  workflow_dispatch:

jobs:
  cleanup:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}