name: GraphQL Mesh Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - "implementations/graphql-mesh/**"

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "graphql-mesh"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'GraphQL Mesh'
      resultsFile: "results-graphql-mesh.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
