name: Graphene Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/graphene/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "graphene"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'Graphene'
      resultsFile: "results-graphene.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
