name: GraphQL Ruby Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/ruby/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "ruby"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'GraphQL Ruby'
      resultsFile: "results-ruby.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
