name: Ariadne Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/ariadne/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "ariadne"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'Ariadne'
      resultsFile: "results-ariadne.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
