name: Pothos Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/pothos/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "pothos"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'Pothos GraphQL'
      resultsFile: "results-pothos.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
