name: Lighthouse Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'implementations/lighthouse/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "lighthouse"
