name: smallrye-graphql Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'implementations/smallrye-graphql/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      # should match folder name
      library: "smallrye-graphql"

  pr-info:
    uses: ./.github/workflows/save-pr-info.yaml
    with:
      pr_number: ${{ github.event.number }}
