name: Flexible Graphql Bundle Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'implementations/flexible-graphql-bundle/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "flexible-graphql-bundle"

  pr-info:
    uses: ./.github/workflows/save-pr-info.yaml
    with:
      pr_number: ${{ github.event.number }}
