name: DGS Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/dgs/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "dgs"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'DGS Framework'
      resultsFile: "results-dgs.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
