name: Spring GraphQL Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'implementations/spring-graphql/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "spring-graphql"

  pr-info:
    uses: ./.github/workflows/save-pr-info.yaml
    with:
      pr_number: ${{ github.event.number }}
