name: Ariadne Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'implementations/ariadne/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "ariadne"
