name: NestJS (SDL First) Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'implementations/nestjs/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "nestjs"
