name: Lighthouse Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/lighthouse/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "lighthouse"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'Lighthouse'
      resultsFile: "results-lighthouse.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
