name: GraphQL Helix Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/helix/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "helix"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'GraphQL Helix'
      resultsFile: "results-helix.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
