name: Federation JVM Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/federation-jvm/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "federation-jvm"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'Federation JVM'
      resultsFile: "results-federation-jvm.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
