name: GraphQL Go Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/graphql-go/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "graphql-go"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'GraphQL Go'
      resultsFile: "results-graphql-go.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
