name: GraphQL Java Kickstart Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/graphql-java-kickstart/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "graphql-java-kickstart"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'GraphQL Java Kickstart'
      resultsFile: "results-graphql-java-kickstart.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
