name: Strawberry GraphQL Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/strawberry-graphql/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "strawberry-graphql"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'Strawberry GraphQL'
      resultsFile: "results-strawberry-graphql.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
