name: Sangria Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/sangria/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "sangria"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'Sangria'
      resultsFile: "results-sangria.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
