name: Caliban Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/caliban/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "caliban"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'Caliban'
      resultsFile: "results-caliban.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
