name: GraphQL Mesh Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "implementations/graphql-mesh/**"

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "graphql-mesh"

  pr-info:
    uses: ./.github/workflows/save-pr-info.yaml
    with:
      pr_number: ${{ github.event.number }}
