name: Async GraphQL Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'implementations/async-graphql/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "async-graphql"
