name: NestJS (SDL First) Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'implementations/nestjs/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "nestjs"

  pr-comment:
    needs: compatibility
    uses: ./.github/workflows/comment.yaml
    with:
      libraryName: 'Nest JS (SDL First)'
      resultsFile: "results-nestjs.md"
    secrets:
      token: ${{ secrets.COMMENT_TOKEN }}
