name: Strawberry GraphQL Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'implementations/strawberry-graphql/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      library: "strawberry-graphql"

  pr-info:
    uses: ./.github/workflows/save-pr-info.yaml
    with:
      pr_number: ${{ github.event.number }}
